### ISSUE TITLE
反馈Docker镜像问题

### ISSUE THREAD

**Issue by Area39** [weev3/LKWA#2]
1.对于XSSI实验，由于docker-compose.yml指定的镜像为nginx，所以无apache.conf配置文件，会出现无法解析.htaccess文件，admin登录后无token。  
2.对于PHAR Deserialization实验，会因为目录权限问题导致无法上传phar包。  
3.对于PHP Object Injection、PHP Object Injection via Cookies、PHP Object Injection (Object Reference)这几个实验，会因为目录权限问题导致无法创建文件。

**Comment by weev3** [comment]
Hi @Area39 , thanks for reporting and my apologies for being late. I will test it again on different environment.

**Comment by weev3** [comment]
Hey @Area39, could you please retest again? I already fixed all bugs that you reported. Thanks

**Comment by weev3** [comment]
Hey @Area39, you can now download public docker image with `docker pull kminthein/lkwa`.
https://hub.docker.com/r/kminthein/lkwa
